language: python
python:
 - "3.6"  
cache: pip
install:
 - pip install -r requirements.txt
 - pip install coveralls
 - pip install codeclimate-test-reporter
services:
  - postgresql
before_script:
  - psql -c "CREATE USER store_owner WITH PASSWORD '12345';"
  - psql -c 'CREATE DATABASE test_store_manager owner store_owner;'
  - psql -c 'CREATE DATABASE store_manager owner store_owner;'

env:
  - DATABASE_TEST_URI='postgresql://store_owner:password12345@localhost:5432/store_manager'
script:
 - pytest --cov-report term-missing --cov=app
 - coveralls

after_success:
 - coveralls
 - codeclimate-test-reporter
