language: python
python:
  "3.6"
install:
  pip install -r requirements.txt
env:
    DATABASE_TEST_URL='postgresql://joshua_kodhe:12345@localhost:5432/test_store_manager'
before_script:
  psql -c "CREATE USER joshua_kodhe WITH PASSWORD '12345';"
  psql -c "CREATE DATABASE test_store_manager OWNER joshua_kodhe;"
script:
  pytest --cov=app
after_success:
  coveralls
